version: '3.8'

services:
  # Main application
  ai-video-generator:
    build: .
    ports:
      - "8503:8503"
    environment:
      - APP_ENV=production
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8503
      - PYTHONPATH=/app
    volumes:
      - ./generated_videos:/app/generated_videos
      - ./temp:/app/temp
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8503/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data:

networks:
  default:
    driver: bridge
      start_period: 30s

  # Optional: Add Redis for caching (future enhancement)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data:
