version: '3.8'

services:
  ai-video-generator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-video-generator-dev
    ports:
      - "8503:8503"
      - "8504:8504"  # For debugging
    environment:
      - APP_ENV=development
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_HEADLESS=false
    volumes:
      - .:/app
      - ./generated_videos:/app/generated_videos
      - ./logs:/app/logs
    command: streamlit run streamlit_app.py --server.port=8503 --server.address=0.0.0.0 --server.headless=false --server.runOnSave=true
    restart: unless-stopped
    networks:
      - ai-video-dev-net

networks:
  ai-video-dev-net:
    driver: bridge
